-- Create the 'content' table to store movies and series
create table content (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  video_url text,
  year integer,
  rating text,
  category text,
  duration text,
  is_new boolean default true,
  type text default 'movie' -- 'movie' or 'series'
);

-- Enable Row Level Security (RLS) - Optional for now but recommended
alter table content enable row level security;

-- Create a policy that allows anyone to read (SELECT)
create policy "Public content are viewable by everyone"
  on content for select
  using ( true );

-- Create a policy that allows authenticated users (admins) to insert/update/delete
-- For now, to keep it simple during dev, we might allow public write or restricting it later
create policy "Public can insert for demo purposes"
  on content for insert
  with check ( true );
  
create policy "Public can update for demo purposes"
  on content for update
  using ( true );

create policy "Public can delete for demo purposes"
  on content for delete
  using ( true );
